version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "6500:5432"
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - ../.env

volumes:
  db:
